- hosts: all
  become: true
  tasks:
     - name: Test machine
       ping:

     - name: Install PHP
       apt:
         name: "{{ item }}"
         update_cache: yes
         cache_valid_time: 86400
         state: installed
       with_items:
         - php5
         - php5-fpm
         - php5-mysql
         - php5-cli

         
