- hosts: all
  become: true
  tasks:
     - name: Test machine
       ping:

     - name: Update repositories cache and install "vim" package
       apt:
         name: "{{ item }}"
         update_cache: yes
         cache_valid_time: 86400
         state: present
       with_items:
         - curl
         - vim
         - htop
