- hosts: all
  become: true

  tasks:
     - name: Check instance ping
       ping:

     - name: Install PHP
       apt:
         name: "{{ item }}"
         update_cache: yes
         cache_valid_time: 86400
         state: present
       with_items:
         - php
         - php-fpm
         - php-mysql
         - php-cli
         - php-xml

     - name: Install MySQL Server & python-mysqldb
       apt:
         name: "{{ item }}"
         update_cache: yes
         cache_valid_time: 86400
         state: latest
       with_items:
         - mysql-server
         - python-mysqldb

     - name: Generate new root password
       command: openssl rand -hex 7 creates=/root/.my.cnf
       register: mysql_root_password

     - name: Remove anonymous users
       mysql_user:
         name: ""
         state: absent
       when: mysql_root_password.changed

     - name: Remove test database
       mysql_db:
         name: test
         state: absent
       when: mysql_root_password.changed

     - name: Output new root password
       debug: msg="New root password is {{mysql_root_password.stdout}}"
       when: mysql_root_password.changed

     - name: Update root password
       mysql_user:
         name: root
         host: "{{ item }}"
         password: "{{ mysql_root_password.stdout }}"
       with_items:
         - "{{ ansible_hostname }}"
         - 127.0.0.1
         - ::1
         - localhost
       when: mysql_root_password.changed

     - name: Create my.cnf
       template: src=templates/mysql/my.cnf dest=/root/.my.cnf
       when: mysql_root_password.changed

     - name: Install nginx
       apt:
         name: nginx
         state: latest

     - name: Start nginx
       service:
         name: nginx
         state: started

     - name: Create nginx config
       template:
         src: templates/nginx/default.conf
         dest: /etc/nginx/sites-available/default
       notify: Restart nginx

     - name: Download WordPress
       get_url:
         url: https://wordpress.org/latest.zip
         dest: /tmp/wordpress.zip

     - name: Install required tools
       apt:
         name: "{{item}}"
         state: installed
       with_items:
         - unzip

     - name: Unzip WordPress
       unarchive:
        remote_src: yes
        src: /tmp/wordpress.zip
        dest: /tmp
        creates: /tmp/wordpress/wp-settings.php

     - name: Create project (WordPress) folder
       file:
          dest: /var/www/exercise2.com
          state: directory

     - name: Copy WordPress files
       command: cp -a /tmp/wordpress/. /var/www/exercise2.com creates=/var/www/exercise2.com/wp-settings.php

     - name: Create WordPress MySQL database
       mysql_db:
         name: wordpress
         state: present

     - name: Create WordPress MySQL users
       mysql_user:
         name: wordpress
         host: localhost
         password: WordpressDBu$er
         priv: wordpress.*:ALL

     - name: Create wp-config
       template:
         src: templates/wordpress/wp-config.php
         dest: /var/www/exercise2.com/wp-config.php

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
