version: "2"

services:
  jenkinsmaster:
    build: jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkinstomcat:
    build: jenkins-tomcat

  jenkinsnginx:
    build: jenkins-nginx
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - jenkinsmaster:jenkins-master
      - jenkinstomcat:jenkins-tomcat

volumes:
  jenkins_home:
