# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # config.vm.box = "hashicorp/precise64"
  config.vm.box = "xenial64"
  config.vm.provision :shell, :privileged => false, :path => "python.sh"


  #Configure ram
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  #configure proxy
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = "http://proxy.corp.globant.com:3128"
    config.proxy.https = "http://proxy.corp.globant.com:3128"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

  ##Configure network forwarding port
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  # config.vm.network "private_network", type: "dhcp"

end
